### ISSUE TITLE
Why re-read & re-write http streams, instead send 401 redirection?

### ISSUE THREAD

**Issue by hbiyik** [beardypig/plugin.video.streamlink#4]
Would be much way easier and less costly? what do you think, kodi can handle rest.
This is only for http streams

**Comment by beardypig** [comment]
It's because some plugins require authentication cookies, specific user-agents, etc.

**Comment by hbiyik** [comment]
You can pipe http header to kodi like:
Http://mysite.com|header1=urlquotedstr&header2=urlquotedstr ....
This way you can pass on, Cookies, Referer, Authentication headers so on
also for hds, there is an already implementation called f4m tester it may help
Great project btw.

i am saying this because asyncore is not the best reactor for python, it eventually creates a IO & cpu load

**Comment by beardypig** [comment]
Yep, could do that. Assuming that syntax works with a 301 redirect. For hls it's not quite the same, oftentimes for encrypted streams the key is on a different domain so that wouldn't work. Doing it this way means everything is handled by Streamlink without too many special cases. However, it's not the best way to do it, that's for sure :-)

**Comment by hbiyik** [comment]
Yeah 301 not 401 :), typing from mobile. Just wanted to hint it up.

For hls,  kodis capabilities only limited with m3u8 files. Rest needs the proxy server.
